# EJERCICIOS TRY/CATCH/FINALLY

## Añadir try/catch/finally en programas ya realizados
Vamos a recuperar el código de los ejercicios siguientes y vamos a añadir la gestión de errores en todos ellos,
utilizando allí donde corresponda try/catch o try/catch/finally:

[Adivina](/practica/ejercicios1/Adivina.java)

[BuscaElementoArray](/practica/ejercicios1/BuscaElementoArray.java)

[CalculadoraHumana](/practica/ejercicios1/CalculadoraHumana.java)

[SerieFibonacci](/practica/ejercicios1/SerieFibonacci.java)

[SumaSerieNumerica](/practica/ejercicios1/SumaSerieNumerica.java)

## Corrige los fallos de compilación
Vamos a recuperar el código del ejercicio siguiente y vamos a añadir la gestión de errores como corresponda

[ReescribeFrase](/practica/ejercicios1/ReescribeFrase.java)

## División
Vamos a desarrollar un programa básico que pregunte por dos operandos al usuario y realice la division entre ellos.
Realizar una correcta gestión de errores usando el bloque completo try/catch/finally

# EJERCICIOS THROW Y THROWS

## División
El ejercicio anterior, vamos a mejorarlo de forma que gestione la excepción antes de que falle la operación división,
es decir, vamos a prevenir el error.
Lo vamos a realizar:
1. A través de una gestión THROW/TRY/CATCH: generamos un error y lo controlamos directamente.
2. A través de una gestión THROW/THROWS: generamos un error y lo lanzamos.

## UsaCasa

Vamos a recuperar el ejercicio UsaCasa. Este ejercicio debía cumplir con dos condiciones:

- La casa debía tener una edad, pero la edad no debería ser inferior a 0.
- La superficie mínima de una casa eran 43.5 m2

Vamos a gestionar estas dos condiciones en forma de excepción.

## Termómetro

Creemos una clase llamada 'Termómetro' con un atributo temperatura. Lanzar una excepción si se intenta fijar una temperatura con un valor menor a -192 o superior a 100.


# EJERCICIOS EXCEPCIONES PERSONALIZADAS

## UsaCasa

Vamos a duplicar el ejercicio que hicimos en el throws para gestionar las dos condiciones con excepciones propias.

## Termómetro

Vamos a duplicar el ejercicio que hicimos en el throws para lanzar una excepción propia llamada
'TemperaturaFueraRangoException'.

## Sistema de acceso

Ejercicio realizado en la UD5. Es un ejercicio muy interesante al que añadir mejoras con la gestión de errores.
